// <auto-generated />
using Eshop.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eshop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Eshop.Domains.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Kvalitní nerezový hrnec pro každodenní vaření.",
                            ImgUrl = "https://mujeshop.cz/hrnec-a.jpg",
                            Name = "Hrnec A",
                            Price = 519.90m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Dřevěná vařečka vhodná na všechny povrchy.",
                            ImgUrl = "https://mujeshop.cz/varecka-b.jpg",
                            Name = "Vařečka B",
                            Price = 99.90m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Nepřilnavá pánev ideální na smažení.",
                            ImgUrl = "https://mujeshop.cz/panev-c.jpg",
                            Name = "Pánev C",
                            Price = 899.00m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Skleněná poklice s odvětráváním.",
                            ImgUrl = "https://mujeshop.cz/poklice-d.jpg",
                            Name = "Poklice D",
                            Price = 199.00m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Velký hrnec vhodný na polévky a vývary.",
                            ImgUrl = "https://mujeshop.cz/hrnec-e.jpg",
                            Name = "Hrnec E",
                            Price = 749.00m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Sada ostrých kuchyňských nožů.",
                            ImgUrl = "https://mujeshop.cz/noze-f.jpg",
                            Name = "Sada nožů F",
                            Price = 1299.00m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Dřevěné krájecí prkénko.",
                            ImgUrl = "https://mujeshop.cz/prkenko-g.jpg",
                            Name = "Prkénko G",
                            Price = 149.90m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Menší rendlík ideální na omáčky.",
                            ImgUrl = "https://mujeshop.cz/rendlik-h.jpg",
                            Name = "Rendlík H",
                            Price = 459.00m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Kovový cedník na těstoviny.",
                            ImgUrl = "https://mujeshop.cz/cednik-i.jpg",
                            Name = "Cedník I",
                            Price = 179.00m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Kuchyňská mísa na míchání.",
                            ImgUrl = "https://mujeshop.cz/misa-j.jpg",
                            Name = "Mísa J",
                            Price = 249.00m
                        },
                        new
                        {
                            Id = 11,
                            Description = "Víceúčelové struhadlo z nerezu.",
                            ImgUrl = "https://mujeshop.cz/struhadlo-k.jpg",
                            Name = "Struhadlo K",
                            Price = 199.90m
                        },
                        new
                        {
                            Id = 12,
                            Description = "Kuchyňská naběračka na polévku.",
                            ImgUrl = "https://mujeshop.cz/lzice-l.jpg",
                            Name = "Lžíce L",
                            Price = 89.90m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
